/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-vrZRcCb11BihSor2p1BzEYR9ijOY4G5OduvpLW0I4thYT1BcsAnIMnmlcdpxV0KUDZtYuIPIsEdjcajAr7KTPVIjsOvW2JDdN-J3hRn9vK1SlKmlnb3f4KEX",
  "tt": "tt-1-uinN7-ANWZ9FjbYo6tOl7ERXOd9p-Jzyl5qRH3Naf8k=",
  "version": "2020-11-20"
}

export default ebconfig;